### ISSUE TITLE
Question about labeller main.py

### ISSUE THREAD

**Issue by petronis** [magnusja/GTSRB-caffe-model#1]
Hi,
I tried to run your main.py in labeller folder but got error 
`No such file or directory: '/home/saulius/Downloads/GTSRB/Final_Test/Images/GT-final_test.test.csv'` its on line 88 what things needs to be in this `GT-final_test.test.csv` file? Because there is nothing like that in GTSRB Image folder like that.
Thank you in advance.

**Comment by magnusja** [comment]
Just downloaded the .zip and for me it's there.
![screen shot 2016-11-26 at 1 39 12 pm](https://cloud.githubusercontent.com/assets/1659457/20644065/cfe9fcde-b3dd-11e6-8575-985a7ce8037f.png)
