### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by amorenew** [magnusja/GTSRB-caffe-model#2]
You have mentioned that your training took six hours.
Unfortunately i have AMD Readon not Nvidia so what hours it could take from me to train
 on CPU + 16g Ram

**Comment by magnusja** [comment]
Hey there,

to be honest I don't know. I assume it takes a couple of days/weeks.

https://groups.google.com/forum/#!topic/caffe-users/Zw6pocQE1Gs
