### ISSUE TITLE
git lfs repository is over its data quota

### ISSUE THREAD

**Issue by luislofer89** [magnusja/GTSRB-caffe-model#3]
Hi,
I am trying to test your solution but when I try to clone the respository with git-lfs i get the next message:

"This repository is over its data quota. Purchase more data packs to restore access."

Please can you enable an alternative resource to download pretrained files?
BR

**Comment by magnusja** [comment]
Sure thing: https://drive.google.com/drive/folders/0B-iC5XyHDwtPT29TaUVaVkg1T0U?usp=sharing
