### ISSUE TITLE
problem using the pretrained GTSRB-caffe-model

### ISSUE THREAD

**Issue by Fnajjar** [magnusja/GTSRB-caffe-model#5]
Hi, 
I used the trained model with the "PipiCNN"(https://github.com/doonny/PipeCNN) to extract the weights.dat file and the data base GTSRB, the problem is that I am having wrong results( all inferences and probabilities are false).
Can you help please!!

![with1024-1](https://user-images.githubusercontent.com/38285230/42564205-78ba017a-8500-11e8-8ff8-2ff62a8f8b51.png)
![with1024-2](https://user-images.githubusercontent.com/38285230/42564206-78d58418-8500-11e8-84d0-1a6f85ea2168.png)
![with 1024-3](https://user-images.githubusercontent.com/38285230/42564207-78ed250a-8500-11e8-854b-e01b990e060c.png)

**Comment by magnusja** [comment]
I dont know this framework, so not sure if there is something wrong.

But maybe it is also because I cropped the images to only contain the sign itself. There is a script for that in the repo. Maybe crop using the script and try if that works better

**Comment by Fnajjar** [comment]
Oh thank you very much for your answer but actually your model is working perfectly I tested it with other images! So thank you for the work you've done.
Apparently, PipeCNN is using CaffeNet, and this model is with AlexNet.
That may have caused wrong results.
So I may retrain the model, with CaffeNet
